---
- name: "Ensure cache directory exists"
  become: true
  ansible.builtin.file:
    path: "{{ erlang_cache_path }}"
    state: directory
    owner: "{{ erlang_user }}"
    group: "{{ erlang_group }}"
    mode: "0755"

- name: "Install Erlang via packages"
  ansible.builtin.include_tasks: package.yml

- name: "Manage EPMD lifecycle"
  ansible.builtin.include_tasks: epmd.yml
  when: erlang_epmd_managed

- name: "Install rebar3"
  ansible.builtin.include_tasks: rebar.yml
  when: erlang_rebar
