---
name: Release to Galaxy

'on':
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Publish to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ansible
        run: pip install ansible-core

      - name: Publish to Galaxy
        run: >
          ansible-galaxy role import
          --token "${{ secrets.GALAXY_API_KEY }}"
          ANXS erlang
